<a href="https://colab.research.google.com/github/SabidHossain/WCF-test-project/blob/master/DiseasePredic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## data preprocessing
df = pd.read_csv("/content/drive/MyDrive/ML Project/dataset.csv") 
# Choose entries with disease
df_new = df #[df['Disease'] == 'Fungal infection'] 
col_distinct_sympton = []
distinct_sympton = []
distinct_disease = []
temp = {}
for i in range(len(df_new)) : 
    r_disease = df_new.iloc[i, 0]
    df_row = df_new[df_new['Disease'] == r_disease] 
    if r_disease not in distinct_disease:
      temp1 = []
      for j in range(len(df_row)):
        for k in range(1,len(df_row.columns)):
          if str(df_row.iloc[j,k])!="nan" and df_row.iloc[j,k].replace(" ","") not in temp1:
              temp1.append(df_row.iloc[j,k].replace(" ",""))
          if str(df_row.iloc[j,k])!="nan" and df_row.iloc[j,k].replace(" ","") not in distinct_sympton:
              distinct_sympton.append(df_row.iloc[j,k].replace(" ",""))
              col_distinct_sympton.append(df_row.iloc[j,k].replace(" ",""))
      temp[r_disease]=temp1
      distinct_disease.append(r_disease)
print(list(temp)[:2])
col_distinct_sympton.append("Disease")

['Fungal infection', 'Allergy']


In [48]:

## data preprocessing
#################################################################### 2
df_processedData = pd.DataFrame(columns = col_distinct_sympton)
df_TestingData = pd.DataFrame(columns = col_distinct_sympton)
#print(col_distinct_sympton)
key_disease_array = []
key_sympton = []
df_new = df#[df['Disease'] == 'Fungal infection'] 
for i in range(len(df_new)) : 
    temp_row = df_new.loc[i,:].values.tolist() 
    temp_row = [str(x).replace(' ', '') for x in temp_row]
    #print(temp_row)

    key_disease = df_new.iloc[i, 0]
    if key_disease not in key_disease_array:
      key_disease_array.append(key_disease)
      key_sympton = []
      for key, val in temp.items():
        if key==key_disease:
          key_sympton = temp[key]     
          break  
    for j in range(len(distinct_sympton)):
      symp = distinct_sympton[j]
      if symp in temp_row:
        #print(symp)
        df_processedData.at[i, symp] = 1
      else:
        df_processedData.at[i, symp] = 0
    df_processedData.at[i,"Disease"] = key_disease

#df_processedData.loc[key_disease,'Disease'] = key_disease  ##this will make single ling
print(df_processedData.head())
df_processedData.to_excel("/content/drive/MyDrive/ML Project/processedDisease.xlsx",sheet_name='DisSymp')

  itching skin_rash  ... yellow_crust_ooze           Disease
0       1         1  ...                 0  Fungal infection
1       0         1  ...                 0  Fungal infection
2       1         0  ...                 0  Fungal infection
3       1         1  ...                 0  Fungal infection
4       1         1  ...                 0  Fungal infection

[5 rows x 132 columns]


In [49]:
########################

## data preprocessing
df_p = pd.read_excel("/content/drive/MyDrive/ML Project/processedDisease.xlsx") 
length_df_p = len(df_p.columns)
df_main=df_p.iloc[:,1:length_df_p]
#df_main = pd.read_csv("/content/training.csv") 
#print(df_main.head())
### Data Preprocessing 
X = df_main.iloc[:, : -1].values
y = df_main.iloc[:, 131:132].values
#print(X)
#print(y)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30)



### train the model with KNeightborsClassifier class of sklearn
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

print(y_pred)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


['Hypertension ' 'Bronchial Asthma' 'Hepatitis C' ... 'Acne'
 'Alcoholic hepatitis' 'Diabetes ']


In [50]:
###Print the result
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(result)
result1= classification_report(y_test,y_pred)
print("Classification Report:",)
print(result1)
result2=accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[42  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 38  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 37]]
Classification Report:
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        42
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        41
                    Alcoholic hepatitis       1.00      1.00      1.00        36
                                Allergy       1.00      1.00      1.00        31
                              Arthritis       1.00      1.00      1.00        34
                       Bronchial Asthma       1.00      1.00      1.00        34
                   Cervical spondylosis       1.00      1.00      1.00        39
                            Chicken pox       1.00      1.00      1.00   

In [51]:




################################################################# 5

#### testing with testing.csv data on prepared classifier
df_test = pd.read_csv("/content/drive/MyDrive/ML Project/testing.csv") 
T_s = df_test.iloc[:, : -1].values
T_d = df_test.iloc[:,-1:]
#print(T_s)
#print(len(T_d.columns))
T_pred = classifier.predict(T_s)
#print(T_d.values.tolist())
#print(T_pred)


###Print the result
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result = confusion_matrix(T_d,T_pred)
print("Confusion Matrix:")
print(result)
result1= classification_report(T_d,T_pred)
print("Classification Report:",)
print(result1)
result2=accuracy_score(T_d,T_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Classification Report:
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         1
                                   AIDS       1.00      1.00      1.00         1
                                   Acne       1.00      1.00      1.00         1
                    Alcoholic hepatitis       1.00      1.00      1.00         1
                                Allergy       1.00      1.00      1.00         1
                              Arthritis       1.00      1.00      1.00         1
                       Bronchial Asthma       1.00      1.00      1.00         1
                   Cervical spondylosis       1.00      1.00      1.00         1
                            Chicken pox       1.00      1.00      1.00         1
                    Chronic 

In [52]:

########################################################## 6

#### testing with real life input data on prepared classifier
# print(distinct_sympton)
input_sympton=['vomiting', 'swelling_of_stomach', 'fatigue',' loss_of_appetite']
# ,'abdominal_pain','yellowing_of_eyes'
# 'chills', 'watering_from_eyes']
# input_sympton=['itching']

for j in range(len(distinct_sympton)):
    symp = distinct_sympton[j]
    if symp in input_sympton:
      df_TestingData.at[1, symp] = 1
    else:
      df_TestingData.at[1, symp] = 0
T_input_sympton = df_TestingData.iloc[:, : -1].values

T_input_pred = classifier.predict(T_input_sympton)
print(T_input_pred)

['Gastroenteritis']


In [53]:
####   Decision tree implementation.
# pred1=StringVar()
def DecisionTree():
## data preprocessing
  df_p = pd.read_excel("/content/drive/MyDrive/ML Project/processedDisease.xlsx") 
  length_df_p = len(df_p.columns)
  df_main=df_p.iloc[:,1:length_df_p]
#df_main = pd.read_csv("/content/training.csv") 
#print(df_main.head())
### Data Preprocessing 
  X = df_main.iloc[:, : -1].values
  y = df_main.iloc[:, 131:132].values
#print(X)
#print(y)
  from sklearn.model_selection import train_test_split

  X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30)


  NameEn = 'sabid'
  from sklearn import tree

  clf3 = tree.DecisionTreeClassifier() 
  clf3 = clf3.fit(X_train,y_train)

  from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
  y_pred=clf3.predict(X_test)
  # print("Decision Tree")
  # print("Accuracy")
  # print(accuracy_score(y_test, y_pred))
  # print(accuracy_score(y_test, y_pred,normalize=False))
  # print("Confusion matrix")
  # conf_matrix=confusion_matrix(y_test,y_pred)
  # print(conf_matrix)
  return clf3 


DecisionTree()

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [55]:
def randomforest():
## data preprocessing
  df_p = pd.read_excel("/content/drive/MyDrive/ML Project/processedDisease.xlsx") 
  length_df_p = len(df_p.columns)
  df_main=df_p.iloc[:,1:length_df_p]
#df_main = pd.read_csv("/content/training.csv") 
#print(df_main.head())
### Data Preprocessing 
  X = df_main.iloc[:, : -1].values
  y = df_main.iloc[:, 131:132].values
#print(X)
#print(y)
  from sklearn.model_selection import train_test_split

  X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30)


  from sklearn.ensemble import RandomForestClassifier
  clf4 = RandomForestClassifier(n_estimators=100)
  clf4 = clf4.fit(X,np.ravel(y))

  # calculating accuracy 
  from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
  y_pred=clf4.predict(X_test)
  # print("Random Forest")
  # print("Accuracy")
  # print(accuracy_score(y_test, y_pred))
  # print(accuracy_score(y_test, y_pred,normalize=False))
  # print("Confusion matrix")
  # conf_matrix=confusion_matrix(y_test,y_pred)
  # print(conf_matrix)

  return clf4
randomforest()
    

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [56]:
def NaiveBayes():
## data preprocessing
  df_p = pd.read_excel("/content/drive/MyDrive/ML Project/processedDisease.xlsx")
  length_df_p = len(df_p.columns)
  df_main=df_p.iloc[:,1:length_df_p]
#df_main = pd.read_csv("/content/training.csv") 
#print(df_main.head())
### Data Preprocessing 
  X = df_main.iloc[:, : -1].values
  y = df_main.iloc[:, 131:132].values
#print(X)
#print(y)
  from sklearn.model_selection import train_test_split
  X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30)

  from sklearn.naive_bayes import GaussianNB
  gnb = GaussianNB()
  gnb=gnb.fit(X,np.ravel(y))

  from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
  y_pred=gnb.predict(X_test)
  # print("Naive Bayes")
  # print("Accuracy")
  # print(accuracy_score(y_test, y_pred))
  # print(accuracy_score(y_test, y_pred,normalize=False))
  # print("Confusion matrix")
  # conf_matrix=confusion_matrix(y_test,y_pred)
  # print(conf_matrix)
  return gnb
NaiveBayes()

GaussianNB(priors=None, var_smoothing=1e-09)

In [64]:
## data preprocessing
df_p = pd.read_excel("/content/drive/MyDrive/ML Project/processedDisease.xlsx")
length_df_p = len(df_p.columns)
df_main=df_p.iloc[:,1:length_df_p]
#df_main = pd.read_csv("/content/training.csv") 
#print(df_main.head())
### Data Preprocessing 
X = df_main.iloc[:, : -1].values
y = df_main.iloc[:, 131:132].values
#print(X)
#print(y)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30)

#create the sub models
estimators = []
model1 = DecisionTree()
estimators.append(('DecTree', model1))
model2 = NaiveBayes()
estimators.append(('bayes', model2))
model3 = randomforest()
estimators.append(('forest', model3))
# create the ensemble model
from sklearn.ensemble import VotingClassifier
ensemble = VotingClassifier(estimators)

#fit model to training data
ensemble.fit(X_train, y_train)
#test our model on the test data
ensemble.score(X_test, y_test)


##########################################################
#### testing with real life input data on prepared classifier
# print(distinct_sympton)
input_sympton=['vomiting', 'swelling_of_stomach', 'fatigue','loss_of_appetite']
# ,'abdominal_pain','yellowing_of_eyes'
# 'chills', 'watering_from_eyes']
# input_sympton=['itching']

for j in range(len(distinct_sympton)):
    symp = distinct_sympton[j]
    if symp in input_sympton:
      df_TestingData.at[1, symp] = 1
    else:
      df_TestingData.at[1, symp] = 0
T_input_sympton = df_TestingData.iloc[:, : -1].values


T_input_tree = model1.predict(T_input_sympton)
T_input_forest = model3.predict(T_input_sympton)
T_input_byes = model2.predict(T_input_sympton)
T_input_ensbl = ensemble.predict(T_input_sympton)
print(T_input_tree)
print(T_input_forest)
print(T_input_byes)
print(T_input_ensbl)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


['Alcoholic hepatitis']
['Alcoholic hepatitis']
['Hepatitis D']
['Alcoholic hepatitis']
